<?xml version="1.0" encoding="utf-8"?><Database Name="Blog" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TUGN\TUGN;Initial Catalog=Blog;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BlogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BanTin" Member="BanTins">
    <Type Name="BanTin">
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenBanTin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="BanTin_ChiTiet" Member="ChiTiets" ThisKey="IDBanTin" OtherKey="IDBanTin" Type="ChiTiet" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTiet" Member="ChiTiets">
    <Type Name="ChiTiet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BanTin_ChiTiet" Member="BanTin" ThisKey="IDBanTin" OtherKey="IDBanTin" Type="BanTin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangNhap" Member="DangNhaps">
    <Type Name="DangNhap">
      <Column Name="IDName" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.BanTin_Delete" Method="BanTin_Delete">
    <Parameter Name="IDBanTin" Parameter="iDBanTin" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DangNhap_Update" Method="DangNhap_Update">
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="passWord" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IDName" Parameter="iDName" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BanTin_Insert" Method="BanTin_Insert">
    <Parameter Name="tenBanTin" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BanTin_SelectAll" Method="BanTin_SelectAll">
    <ElementType Name="BanTin_SelectAllResult">
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenBanTin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BanTin_SelectID" Method="BanTin_SelectID">
    <Parameter Name="IDBanTin" Parameter="iDBanTin" Type="System.Int32" DbType="Int" />
    <ElementType Name="BanTin_SelectIDResult">
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenBanTin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BanTin_Update" Method="BanTin_Update">
    <Parameter Name="tenBanTin" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IDBanTin" Parameter="iDBanTin" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ChiTiet_Delete" Method="ChiTiet_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ChiTiet_Insert" Method="ChiTiet_Insert">
    <Parameter Name="tieuDe" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ngayDang" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDBanTin" Parameter="iDBanTin" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ChiTiet_LanXem" Method="ChiTiet_LanXem">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="lanXem" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ChiTiet_SELECT" Method="ChiTiet_SELECT">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="ChiTiet_SELECTResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTiet_SelectAll" Method="ChiTiet_SelectAll">
    <ElementType Name="ChiTiet_SelectAllResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTiet_SelectBT" Method="ChiTiet_SelectBT">
    <Parameter Name="IDBanTin" Parameter="iDBanTin" Type="System.Int32" DbType="Int" />
    <ElementType Name="ChiTiet_SelectBTResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTiet_SelectHome" Method="ChiTiet_SelectHome">
    <ElementType Name="ChiTiet_SelectHomeResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTiet_SelectID" Method="ChiTiet_SelectID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="ChiTiet_SelectIDResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTiet_SelectRandom" Method="ChiTiet_SelectRandom">
    <Parameter Name="IDBanTin" Parameter="iDBanTin" Type="System.Int32" DbType="Int" />
    <ElementType Name="ChiTiet_SelectRandomResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDBanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTiet_SLX" Method="ChiTiet_SLX">
    <Parameter Name="lanXem" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ChiTiet_Update" Method="ChiTiet_Update">
    <Parameter Name="tieuDe" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="noiDung" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DangNhap_Delete" Method="DangNhap_Delete">
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DangNhap_Insert" Method="DangNhap_Insert">
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="passWord" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DangNhap_Search" Method="DangNhap_Search">
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="passWord" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="DangNhap_SearchResult">
      <Column Name="IDName" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DangNhap_SelectAll" Method="DangNhap_SelectAll">
    <ElementType Name="DangNhap_SelectAllResult">
      <Column Name="IDName" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>